#!/usr/bin/env python3
"""Emit the bounded, context-specific Lean proof for the 12509/15 exclusion.

The monolithic kernel check exceeds its memory budget. Each leaf declaration
checks at most 100 rule occurrences; parent declarations use the proved split
composition lemma. Sharing node syntax never shares a conclusion across prefixes.
The emitted theorem must still be compiled and audited by Lean.
"""
import argparse
import hashlib
import json
from pathlib import Path

from check_exclusion import check_exclusion

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "results/2026-10-03-12509-limit15-exclusion.json"
EXPECTED = "1342d0804442d7645d56e56d4a2a05e9cc2007555d3357191a135a512443415e"
SUBTREE_LIMIT = 100


def render(document):
    nodes = document["nodes"]
    sizes = {}

    def size(index):
        # Cache syntactic subtree sizes only, never checker truth.
        if index not in sizes:
            node = nodes[index]
            sizes[index] = (1 + sum(size(j) for _, j in node[1])
                            if node[0] == "split" else 1)
        return sizes[index]

    def literal(values):
        return "[" + ",".join(map(str, values)) + "]"

    declarations = []

    def emit(index, prefix, remaining):
        node = nodes[index]
        if size(index) <= SUBTREE_LIMIT:
            proof = "by decide +kernel"
        else:
            children = [emit(j, prefix + [v], remaining - 1) for v, j in node[1]]
            edges = "[" + ",".join(f"({v},{j})" for v, j in node[1]) + "]"
            proof = ("by\n"
                     f"  apply checkExclusionWith_split (edges := {edges})\n"
                     "    (by decide) (by decide +kernel) (by decide +kernel)\n"
                     "  intro e he\n"
                     "  simp only [List.mem_cons, List.not_mem_nil, or_false] at he\n"
                     "  rcases he with " + " | ".join("rfl" for _ in children) + "\n"
                     + "\n".join(f"  · exact {child}" for child in children))
        name = f"exclusionPart{len(declarations)}"
        declarations.append(
            f"private theorem {name} : checkExclusionWith exclusionTree12509.lookup\n"
            f"    12509 {literal(prefix)} {prefix[-1]} {remaining} {index} = true := {proof}\n")
        return name

    root = emit(document["root"], [1], 15)
    blob = json.dumps(json.dumps(nodes, separators=(",", ":")))
    header = '''-- Generated by scripts/export_lean_exclusion.py; do not edit the data/proof fragments.
-- Source SHA256: ''' + EXPECTED + '''
import ScholzBrauer.ExclusionTree
import ScholzBrauer.Example12509

namespace ScholzBrauer

-- Sequential checking bounds retained elaboration state.
set_option Elab.async false
set_option maxRecDepth 65536
set_option maxHeartbeats 2000000

private noncomputable def exclusionTree12509 : ExclusionTree := exclusion_tree% ''' + blob + "\n\n"
    footer = f'''
/-- Every chain with at most 15 additions is excluded, in its actual prefix context. -/
theorem exclusion12509_fifteen_checked :
    checkExclusionWith exclusionTree12509.lookup 12509 [1] 1 15 {document['root']} = true :=
  {root}

/-- Stronger formal lower bound; the optimum 17 is still not proved here. -/
theorem sixteen_le_length12509 : 16 ≤ additionChainLength 12509 := by
  have hne := additionChainSteps_nonempty (n := 12509) (r := 17)
    chain12509 chain12509_valid (by decide) (by decide)
  have hlo := checkExclusionWith_lower_bound exclusion12509_fifteen_checked hne
  omega

end ScholzBrauer
'''
    return header + "\n".join(declarations) + footer, len(declarations)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    raw = SOURCE.read_bytes()
    if hashlib.sha256(raw).hexdigest() != EXPECTED:
        raise ValueError("exclusion input hash changed")
    document = json.loads(raw)
    checked = check_exclusion(document, target=12509, max_steps=15)
    source, count = render(document)
    with args.output.open("x") as out:
        out.write(source)
    print(json.dumps({"source_sha256": EXPECTED, "subtree_limit": SUBTREE_LIMIT,
                      "proof_declarations": count, "independent_check": checked,
                      "lean_proof": False}, indent=2))


if __name__ == "__main__":
    main()
