#!/usr/bin/env python3
"""Export a bounded index certificate as kernel-checkable Lean value replay.

Python checks are an early rejection aid. Only compiling the emitted theorems
checks the result in Lean; no general format-equivalence theorem is asserted.
Source-chain provenance is deliberately not used to justify replay.
"""
import argparse
import json
from pathlib import Path
import re

from check_certificate import check_document


MAX_EXPONENT = 64
MAX_ADDITIONS = 128
HEADER = """import ScholzBrauer.Certificate

/-! Generated by scripts/export_lean_certificate.py. Finite replay witnesses,
not a proof of the Hansen generator, format equivalence, or optimality. -/
namespace ScholzBrauer.Exported

"""
FOOTER = "end ScholzBrauer.Exported\n"


def value_certificate(document, *, exponent, additions):
    """Check explicit expectations and resource caps before integer replay."""
    if type(exponent) is not int or not 1 <= exponent <= MAX_EXPONENT:
        raise ValueError("export exponent must be in 1..64")
    if type(additions) is not int or not 0 <= additions <= MAX_ADDITIONS:
        raise ValueError("export additions must be in 0..128")
    if not isinstance(document, dict):
        raise ValueError("expected certificate object")
    if not isinstance(document.get("target"), dict):
        raise ValueError("expected target object")
    if not isinstance(document.get("pairs"), list):
        raise ValueError("expected pair list")
    values = check_document(document, exponent=exponent, additions=additions)
    steps = [(values[left], values[right]) for left, right in document["pairs"]]
    return steps, values


def render_fixture(document, *, name, exponent, additions):
    # A restricted suffix under a fixed prefix cannot inject Lean commands or
    # become a reserved word. Certificate numerals come only from exact replay.
    if not isinstance(name, str) or not re.fullmatch(r"[A-Za-z][A-Za-z0-9_]{0,63}", name):
        raise ValueError("invalid fixture name")
    steps, values = value_certificate(document, exponent=exponent, additions=additions)
    base = "fixture_" + name
    pairs = ",\n   ".join(f"({a}, {b})" for a, b in steps)
    chain = ", ".join(map(str, values))
    return f"""def {base}_steps : List Step :=
  [{pairs}]

def {base}_values : List ℕ :=
  [{chain}]

theorem {base}_replay :
    replay {base}_steps = some {base}_values := by decide

theorem {base}_count : {base}_steps.length = {additions} := by decide

theorem {base}_valid : IsAdditionChain {base}_values :=
  replay_sound {base}_replay

theorem {base}_bound : additionChainLength (2 ^ {exponent} - 1) ≤ {additions} :=
  certificate_upper_bound {base}_replay (by decide) (by decide)

"""


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("certificate", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--name", required=True)
    parser.add_argument("--exponent", required=True, type=int)
    parser.add_argument("--additions", required=True, type=int)
    args = parser.parse_args()
    if args.output.exists():
        raise FileExistsError(args.output)
    document = json.loads(args.certificate.read_text())
    source = HEADER + render_fixture(document, name=args.name,
        exponent=args.exponent, additions=args.additions) + FOOTER
    with args.output.open("x") as output:
        output.write(source)
    print(json.dumps({"output": str(args.output), "exponent": args.exponent,
                      "additions": args.additions, "lean_build_run": False}))


if __name__ == "__main__":
    main()
