import ScholzBrauer

#print axioms ScholzBrauer.append_sum
#print axioms ScholzBrauer.replay_sound
#print axioms ScholzBrauer.replay_length
#print axioms ScholzBrauer.replay_upper_bound
#print axioms ScholzBrauer.certificate_upper_bound
#print axioms ScholzBrauer.chain12509_direct
#print axioms ScholzBrauer.length12509_le_seventeen
#print axioms ScholzBrauer.fourteen_le_length12509

#print axioms ScholzBrauer.doublingSteps_length
#print axioms ScholzBrauer.doublingSteps_replay
#print axioms ScholzBrauer.replayFrom_append
#print axioms ScholzBrauer.mersenne_block_identity
#print axioms ScholzBrauer.brauerBlock_length
#print axioms ScholzBrauer.brauerBlock_replay
#print axioms ScholzBrauer.brauerBlock_upper_bound

#print axioms ScholzBrauer.starSourceFrom_length
#print axioms ScholzBrauer.starSourceFrom_endpoint
#print axioms ScholzBrauer.starSourceFrom_valid
#print axioms ScholzBrauer.starCertificateFrom_length
#print axioms ScholzBrauer.starCertificateFrom_replay
#print axioms ScholzBrauer.starLift_certificate
#print axioms ScholzBrauer.starLift_upper_bound
#print axioms ScholzBrauer.scholz_of_optimal_star
#print axioms ScholzBrauer.starIncrements12509_checked
#print axioms ScholzBrauer.starSource12509_eq
#print axioms ScholzBrauer.starChain12509_valid
#print axioms ScholzBrauer.starLift12509_certificate
#print axioms ScholzBrauer.mersenne12509_length_le_12526

#print axioms ScholzBrauer.hansenSourceFrom_length
#print axioms ScholzBrauer.hansenPairsFrom_length
#print axioms ScholzBrauer.hansenPairsFrom_replay
#print axioms ScholzBrauer.hansenSourceFrom_valid
#print axioms ScholzBrauer.hansenAnchorFrom_latest
#print axioms ScholzBrauer.hansenSourceFrom_endpoint
#print axioms ScholzBrauer.hansenMarksFrom_stored_max
#print axioms ScholzBrauer.hansenFrom_split
#print axioms ScholzBrauer.hansen_latest_anchor_step
#print axioms ScholzBrauer.hansen_final_mark
#print axioms ScholzBrauer.hansen12509_checked
#print axioms ScholzBrauer.hansenSource12509_eq
#print axioms ScholzBrauer.hansen12509_source_replay
#print axioms ScholzBrauer.hansen12509_marks
#print axioms ScholzBrauer.hansen12509_source_count

#print axioms ScholzBrauer.hansenNextMark_bounds_prefix
#print axioms ScholzBrauer.hansenShiftMax_eq_gap
#print axioms ScholzBrauer.hansenShiftDemands_le_max
#print axioms ScholzBrauer.hansenShiftCaps_head
#print axioms ScholzBrauer.hansenShiftCaps_length
#print axioms ScholzBrauer.hansenShiftCaps_telescope
#print axioms ScholzBrauer.hansenShiftCaps_sum
#print axioms ScholzBrauer.hansenShiftCaps_budget
#print axioms ScholzBrauer.hansen12509_shift_caps
#print axioms ScholzBrauer.hansen12509_shift_sum
#print axioms ScholzBrauer.hansen12509_shift_budget

#print axioms ScholzBrauer.Exported.fixture_singleton_replay
#print axioms ScholzBrauer.Exported.fixture_singleton_count
#print axioms ScholzBrauer.Exported.fixture_singleton_valid
#print axioms ScholzBrauer.Exported.fixture_singleton_bound
#print axioms ScholzBrauer.Exported.fixture_interleaved29_replay
#print axioms ScholzBrauer.Exported.fixture_interleaved29_count
#print axioms ScholzBrauer.Exported.fixture_interleaved29_valid
#print axioms ScholzBrauer.Exported.fixture_interleaved29_bound

#print axioms ScholzBrauer.mersenne_mod_two
#print axioms ScholzBrauer.two_pow_mul_odd_unique
#print axioms ScholzBrauer.shiftedMersenne_eq_iff
#print axioms ScholzBrauer.shiftedMersenne_pos
#print axioms ScholzBrauer.shiftedMersenne_succ
#print axioms ScholzBrauer.shiftedMersenne_base_sum
#print axioms ScholzBrauer.shiftedMersenne_nodup

#print axioms ScholzBrauer.mem_hansenRow
#print axioms ScholzBrauer.hansenLabels_anchor
#print axioms ScholzBrauer.hansenLabels_base
#print axioms ScholzBrauer.hansenLabels_tail
#print axioms ScholzBrauer.hansenLabels_downward
#print axioms ScholzBrauer.hansenLabels_length
#print axioms ScholzBrauer.hansenLabels_source_base
#print axioms ScholzBrauer.hansenLabels_exponent
#print axioms ScholzBrauer.hansenLabels_positive
#print axioms ScholzBrauer.hansenLabels_nodup
#print axioms ScholzBrauer.hansenSourceFrom_mem
#print axioms ScholzBrauer.hansenSourceFrom_bound
#print axioms ScholzBrauer.hansenLabels_envelope
#print axioms ScholzBrauer.hansenLabels_base_sums
#print axioms ScholzBrauer.hansenLabels_closed
#print axioms ScholzBrauer.mem_hansenLift
#print axioms ScholzBrauer.shiftedMersenne_le_endpoint
#print axioms ScholzBrauer.hansenLift_chain
#print axioms ScholzBrauer.additionChain_exists_replay
#print axioms ScholzBrauer.hansenLift_certificate
#print axioms ScholzBrauer.hansenLift_upper_bound
#print axioms ScholzBrauer.scholz_of_optimal_hansen
#print axioms ScholzBrauer.hansenLift12509_chain
#print axioms ScholzBrauer.hansenLift12509_certificate
#print axioms ScholzBrauer.mersenne12509_length_le_12525

#print axioms ScholzBrauer.ChainReach.mono
#print axioms ScholzBrauer.ChainReach.endpoint_le
#print axioms ScholzBrauer.ChainReach.doubling_bound
#print axioms ScholzBrauer.replayFrom_reaches
#print axioms ScholzBrauer.additionChain_reaches
#print axioms ScholzBrauer.additionChain_extension_reaches
#print axioms ScholzBrauer.checkExclusion_sound
#print axioms ScholzBrauer.checkExclusion_excludes
#print axioms ScholzBrauer.checkExclusion_excludes_extension
#print axioms ScholzBrauer.checkExclusion_lower_bound
#print axioms ScholzBrauer.exclusionSeven_checked
#print axioms ScholzBrauer.length_seven_eq_four
