import ScholzBrauer.Certificate

/-! Generated by scripts/export_lean_certificate.py. Finite replay witnesses,
not a proof of the Hansen generator, format equivalence, or optimality. -/
namespace ScholzBrauer.Exported

def fixture_singleton_steps : List Step :=
  []

def fixture_singleton_values : List ℕ :=
  [1]

theorem fixture_singleton_replay :
    replay fixture_singleton_steps = some fixture_singleton_values := by decide

theorem fixture_singleton_count : fixture_singleton_steps.length = 0 := by decide

theorem fixture_singleton_valid : IsAdditionChain fixture_singleton_values :=
  replay_sound fixture_singleton_replay

theorem fixture_singleton_bound : additionChainLength (2 ^ 1 - 1) ≤ 0 :=
  certificate_upper_bound fixture_singleton_replay (by decide) (by decide)

def fixture_interleaved29_steps : List Step :=
  [(1, 1),
   (2, 1),
   (3, 3),
   (6, 6),
   (12, 3),
   (15, 15),
   (30, 30),
   (60, 60),
   (120, 120),
   (240, 15),
   (255, 255),
   (510, 1),
   (510, 510),
   (1020, 1020),
   (2040, 2040),
   (4080, 15),
   (4080, 4080),
   (8160, 8160),
   (16320, 16320),
   (32640, 32640),
   (65280, 65280),
   (130560, 511),
   (131071, 131071),
   (262142, 262142),
   (524284, 524284),
   (1048568, 1048568),
   (2097136, 2097136),
   (4194272, 4194272),
   (8388544, 8388544),
   (16777088, 16777088),
   (33554176, 33554176),
   (67108352, 67108352),
   (134216704, 134216704),
   (268433408, 268433408),
   (536866816, 4095)]

def fixture_interleaved29_values : List ℕ :=
  [1, 2, 3, 6, 12, 15, 30, 60, 120, 240, 255, 510, 511, 1020, 2040, 4080, 4095, 8160, 16320, 32640, 65280, 130560, 131071, 262142, 524284, 1048568, 2097136, 4194272, 8388544, 16777088, 33554176, 67108352, 134216704, 268433408, 536866816, 536870911]

theorem fixture_interleaved29_replay :
    replay fixture_interleaved29_steps = some fixture_interleaved29_values := by decide

theorem fixture_interleaved29_count : fixture_interleaved29_steps.length = 35 := by decide

theorem fixture_interleaved29_valid : IsAdditionChain fixture_interleaved29_values :=
  replay_sound fixture_interleaved29_replay

theorem fixture_interleaved29_bound : additionChainLength (2 ^ 29 - 1) ≤ 35 :=
  certificate_upper_bound fixture_interleaved29_replay (by decide) (by decide)

end ScholzBrauer.Exported
